### ISSUE TITLE
capture citation list and metadata

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/metrics-service#14]
From the scholix service, capture the citation DOI and then lookup the citation metadata, and store all of this in a database for future use.

**Comment by rushirajnenuji** [comment]
Progress: Worked on this with the commit https://github.com/DataONEorg/metrics-service/commit/692c8c704c66c534ffa38dd0fd3e5fa096ad35df and https://github.com/DataONEorg/metrics-service/commit/df3ad0438d5697635c3672f8fa61ca80c34fcbf0
References: https://github.com/DataONEorg/metrics-service/issues/18 and https://github.com/DataONEorg/metrics-service/issues/19

TODO:  Revisit the algorithm on how we're checking citations for DOIs from the CROSSREF services.

**Comment by rushirajnenuji** [comment]
Solved with #18 #19
