### ISSUE TITLE
Design Citation storage schema

### ISSUE THREAD

**Issue by rushirajnenuji** [DataONEorg/metrics-service#18]

**Comment by rushirajnenuji** [comment]
Based on the citation list I've gathered the following information that we could use to display the list.

- `id` SERIAL,  -- identifier of the record
- `target_id` TEXT,  -- target(dataset that was cited) identifier
- `source_id` TEXT,   -- source identifier
- `origin` TEXT,  -- authors of the source dataset
- `title` TEXT,  -- publisher e.g. dataONE
- `year_of_publishing`, INTEGER,  -- YOP for the source dataset
- `link_publication_date` TEXT,   -- the date when this relation was first recorded by CROSSREF.

For the counts of the citations of a given dataset we could simply check the counts of the records available in this citations table based on the target_id.
For the citations modal we could retrieve all the information of a given dataset identifier based on the target_id and form citations list based on the source information.

TODO: I could not find the API that we could use to query the doi resolving service.
However there is this CROSSREF endpoint that could be sued to resolve the DOIs.
`api.crossref.org` and `api.crossref.org/works `

For implementation of https://github.com/DataONEorg/metrics-service/issues/19 the Python service would visit this endpoint for every citation found for our datasets and gather this metadata and store it into the database described above.

**Comment by rushirajnenuji** [comment]
[Report JSON](https://gist.github.com/rushirajnenuji/ad08dc9f6f2bbce2a5b78ba5bd70a65e) - This is a Citation record obtained from Crossref

[Metadata JSON](https://gist.github.com/rushirajnenuji/9fd3ad7d93dee5d2603c1af830fdd20e) - Metadata about the source that cited our dataset obtained from DOI resolve end-point

[Meeting notes](https://hpad.dataone.org/IYJgrAxgHGCcsFoAsB2VywGYBGDsDYBTCBTARkJX2CjIBM6RCg==?both)

Solved with the commits https://github.com/DataONEorg/metrics-service/commit/692c8c704c66c534ffa38dd0fd3e5fa096ad35df and https://github.com/DataONEorg/metrics-service/commit/363548cb095c8d27c6839cb869737f06a64d5beb

**Comment by mbjones** [comment]
Added the [meeting notes](https://hpad.dataone.org/IYJgrAxgHGCcsFoAsB2VywGYBGDsDYBTCBTARkJX2CjIBM6RCg) from the Meeting here for later reference:

# MDC Metting Notes


### June 14, 2018

Attendees: Rushiraj, Chris, Lauren

Agenda:
- Tickets:
    - Metrics service is up and running 
    - UI is ready
    - Citation service ready with metadata
- Discuss UI with the team
    - The width problem
        - Different themes have different widths
    - Button styling
    - TODOs:
        - Copy citation success message not getting displayed
        - Responsive design
        - Number Abbreviator: 1K, 1M, ~
- Problem with GUnicorn
    - Question: How to keep it running continuously?!

Discussions:
- 597 : Metrics model
    - Single model that does a single fetch 
    - Metric model: Move the settings (hard-coded values like URL, startDate, endDate, etc.) into the AppModel because they're config params
- Check the start date: should be datePublished date or the start of time
- Change the metricRequest to sync function.
- Code in DataONEObject for bytes, KB, GB, so on...
- Responsive CSS view can be worked on after the MVP work is done
- Would be efficient to save the doc in a column and access it.
    - check out postgres json 

- Citation Storage: 
    - Store the CrossRef JSON documents directly in the metrics-service database, and extract key field values into other columns.
