### ISSUE TITLE
Solr query reserved characters need to be escaped

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/metrics-service#42]
https://github.com/DataONEorg/metrics-service/blob/0de89d668b85efc5cc7a8cf8089d799d877e7e81/src/d1_metrics_service/d1_metrics_service/metricsreader.py#L681

e.g.:
```python
SOLR_RESERVED_CHAR_LIST = [
  '+', '-', '&', '|', '!', '(', ')', '{', '}', '[', ']', '^', '"', '~', '*', '?', ':'
]

def escapeSolrQueryTerm(term):
  term = term.replace('\\', '\\\\')
  for c in SOLR_RESERVED_CHAR_LIST:
    term = term.replace(c, '\{}'.format(c))
  return term

identifier = '(("' + '") OR ("'.join(map(escapeSolrQueryTerm, PIDs)) + '"))'
```

**Comment by rushirajnenuji** [comment]
Solved with the commit: https://github.com/DataONEorg/metrics-service/commit/355ab8172b3ae88d003829c4ee67ab9dcb87f1a8

- Added the `quoteTerm` and `escapeSolrQueryTerm` functionalities for both the MetricsReader and PIDResolution Python modules.
