### ISSUE TITLE
solr query reserved characters need to be escaped in query term

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/metrics-service#43]
https://github.com/DataONEorg/metrics-service/blob/0de89d668b85efc5cc7a8cf8089d799d877e7e81/src/d1_metrics_service/d1_metrics_service/metricsreader.py#L387

See #42

**Comment by rushirajnenuji** [comment]
Solved with the commit: https://github.com/DataONEorg/metrics-service/commit/355ab8172b3ae88d003829c4ee67ab9dcb87f1a8

- Added the `quoteTerm` and `escapeSolrQueryTerm` functionalities for both the MetricsReader and PIDResolution Python modules.
