### ISSUE TITLE
PID not retrieving citations from the metrics service while SID does

### ISSUE THREAD

**Issue by vchendrix** [DataONEorg/metrics-service#57]
We have a dataset in ESS-DIVE (https://data.ess-dive.lbl.gov) that has  4 citations. When the SID is referenced (doi:10.3334/CDIAC/OTG.NDP045) it returns the citations. However when the PID is referenced (ess-dive-72366fad1afb734-20180823T161614624764) no citations show up.

+ https://knb.ecoinformatics.org/view/doi:10.3334/CDIAC/OTG.NDP045
+ https://knb.ecoinformatics.org/view/ess-dive-72366fad1afb734-20180823T161614624764

**Comment by rushirajnenuji** [comment]
Solved by solving the bug in the pid_Resolution algorithm.
